# Generated by Django 5.2.11 on 2026-02-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Mapsdan joyni ulashgan linkni bu yerga qo‘ying', max_length=500, null=True, verbose_name='Xarita havolasi (Google Maps)'),
        ),
    ]
